### ISSUE TITLE
Item dupe

### ISSUE THREAD

**Issue by mvolotov** [MineVid/dtlTraders-plus-#12]
Good afternoon!

I found a bug on my server. If you hover the cursor over an item in the store, and then click a combination like 3+e, where 3 is a slot from the hotbar, and e is the closure of the inventory, then the item gets into the selected hotbar cell for free and the store closes.

PaperMC: 1.16.5#768
dtlTraders-plus: 6.4.1

**Comment by notbike** [comment]
confirmed, dupe worked on 1.18.1, purpur, plugin ver. 6.4.7

**Comment by MinevidOld** [comment]
The number thing is fixed in my test version. Will post a update as soon as possible. (Currently at work)

**Comment by MinevidOld** [comment]
Fixed in latest version (6.4.9)
