### ISSUE TITLE
Switching Items over Numbers not Working

### ISSUE THREAD

**Issue by TastaMax** [MineVid/dtlTraders-plus-#13]
Hey Guys,

I have a problem with inventory and item sorting. 
Unfortunately, when I bring an item to slot 1 by clicking "1", it doesn't work.
Double-clicking items to add them to the stack doesn't work either.

Sorry for the bad english skills xD

**Comment by TastaMax** [comment]
Im using PAPER 1.18.1 Build #204

**Comment by MinevidOld** [comment]
Is this only when a dtlTraders shop is opened?

**Comment by TechGe3ks** [comment]
> Is this only when a dtlTraders shop is opened?

No this occurs all the time

**Comment by MinevidOld** [comment]
Fixed in the latest build (6.4.10)
