### ISSUE TITLE
"Buy and Keep" command items function similar to "Buy and Run" and are used immediately without player action.

### ISSUE THREAD

**Issue by ManfranMike** [MineVid/dtlTraders-plus-#2]
As the title states. "Buy and Keep" command items will run shortly after purchasing without the player using right-click with the item.

Steps to Reproduce:
1. Add a Command Item to a shop and set as "Buy and Keep"
2. Add the command "say %player%" to the item
3. Purchase the item and the command will immediately run (sometimes the item can be briefly seen in the hotbar)

![](https://cdn.discordapp.com/attachments/529708707089612821/761817627710324745/unknown.png)

GIFs to demonstrate: [https://cdn.discordapp.com/attachments/529708707089612821/761819342915502090/tradersbug1.gif](url)

[https://cdn.discordapp.com/attachments/529708707089612821/761831473392910356/tradersbug2.gif](url)

List of Plugins (26): LuckPerms, WorldEdit, PlaceholderAPI, Oh_the_dungeons_youll_go, Multiverse-Core, ProtocolLib, WorldGuard, Multiverse-Portals, Vault, MyCommand, dynmap, Coins, ChestShop, Chunky, Essentials, SinglePlayerSleep, ChunkyBorder, HolographicDisplays, DeadChest, DecoHeads, Citizens, EssentialsChat, SuperVanish, dtlTradersPlus, CrateReloaded, DiscordSRV

**Comment by MinevidOld** [comment]
Got this fixed in my test version!
