### ISSUE TITLE
BUG If Obtainable item is AIR (dtlTradersPlus 6.4.29, Minecraft 1.21.1)

### ISSUE THREAD

**Issue by Leon-CZ** [MineVid/dtlTraders-plus-#25]
If I change directly in shopname.yml that obtainable item is AIR

Example:
          obtainable-items:
            obtainable-item-0:
              item:
                ==: org.bukkit.inventory.ItemStack
                v: 2865
                type: AIR

then when I select BUY, SELL, TRADE in the bottom right corner of the EDIT GUI so the ITEM icon stays in my hand and the selection doesn't change.

I want to achieve that when players TRADE they receives the ITEM from the command and not from the "Change obtainable items" GUI

Example:
          on-trade-commands:
            '0':
              executor: CONSOLE
              command: lp user %player% permission set ...
            '1':
              executor: CONSOLE
              command: give %player% written_book[written_book_content={pages:...

**Comment by wolfebersahd** [comment]
This issue was caused my you manipulating the itemstack material to AIR when we advised you that an obtained item is needed.

To achieve what you want, why don't you just give the written book as an obtained item? why does it have to be given via a command?

**Comment by Leon-CZ** [comment]
Because I want the player's name to be in a certain place in the book.
And so far it only works with this code:
...,{"text":" **%player%**", "color":"...

But this problem is now solved - an obtained item is **always** needed!
