### ISSUE TITLE
BUG - Entering item names with no color-code or `&r` defaults the item name back to italicized on restart/reload.

### ISSUE THREAD

**Issue by wolfebersahd** [MineVid/dtlTraders-plus-#4]
Steps to reproduce:
1. Load server with all required plugins on 1.16.3
2. Create new shop
3. Give or create items with &rNAME in order to remove all coloricode
4. Add item to shop
5. Item name is not italicized
6. Restart server, reload server, or reload dtl traders
7. Open shop and observer item

RESULT (10/10):
Item name changes to italicized.

EXPECTED RESULTS:
Item name should remain as initially setup.

Versions:
 - dtlTrader (6.2.6)
 - PaperMC (paper-251) for 1.16.3

Before restart
![not italics](https://user-images.githubusercontent.com/9948243/97716560-23a16e80-1a9a-11eb-9e9c-ee4ce1b6a799.gif)

After restart
![2020-10-30_10 18 11](https://user-images.githubusercontent.com/9948243/97716639-3fa51000-1a9a-11eb-8fdc-8126e4b99842.png)

**Comment by wolfebersahd** [comment]
i tried adding &r manually to the config... still didn't help
![image](https://user-images.githubusercontent.com/9948243/97717254-f86b4f00-1a9a-11eb-9579-af3b9635a6ae.png)

**Comment by MinevidOld** [comment]
Fixed in 6.3.0
